Lab 10
kse-ua/introduction-to-it pull request #106
Opened 2021-12-16 17:05 UTC by YaroslavKSE

2021-12-19 22:37 UTC, tshemsedinov requested changes
- Improve code style in js
- Try to optimize using map instead of for loop
- Don not modify incoming structures like list and point, create new one instead

2021-12-19 22:37 UTC, tshemsedinov commented on lecture_notes/10 refactoring/1-not-optimal.js
> +"use strict";
We use double quote

2021-12-20 09:02 UTC, YaroslavKSE commented on lecture_notes/10 refactoring/1-not-optimal.js
> +"use strict";
I use double quote too)

2021-12-24 09:11 UTC, tshemsedinov commented on lecture_notes/10 refactoring/1-not-optimal.js
> +    const y = Number(Y);
use parseInt Luke

2021-12-24 09:12 UTC, tshemsedinov commented on lecture_notes/10 refactoring/1-not-optimal.js
> +    };
Better to move to file-global scope

2021-12-24 09:13 UTC, tshemsedinov commented on lecture_notes/10 refactoring/1-not-optimal.js
> +  rl.question("Enter coordinate Y: ", function (Y) {
Why `function`? use lambdas, X and Y are not camelCase

2021-12-24 09:24 UTC, closed without merging