Lab 10
kse-ua/introduction-to-it pull request #113
Opened 2021-12-17 08:24 UTC by roflmyrlok

2021-12-19 22:18 UTC, tshemsedinov requested changes
- Try to optimize using map instead of for loop
- Don not modify incoming structures like list and point, create new one instead
- Waiting for js version

2021-12-19 22:18 UTC, tshemsedinov commented on lecture_notes/10 refactoring/1-not-optimal.py
> +shift({'x': 10, 'y': -5}, polyline);
Semicolon in python?

2021-12-19 22:18 UTC, tshemsedinov commented on lecture_notes/10 refactoring/3-optimized.py
> +    point = json.loads(point)
Don't rewrite incoming parameters

2021-12-19 22:18 UTC, tshemsedinov commented on lecture_notes/10 refactoring/3-optimized.py
> +    return points
Don't rewrite incoming parameters

2021-12-20 10:10 UTC, roflmyrlok commented on lecture_notes/10 refactoring/3-optimized.py
> +    point = json.loads(point)
please, check the solution

2021-12-20 10:10 UTC, roflmyrlok commented on lecture_notes/10 refactoring/1-not-optimal.py
> +shift({'x': 10, 'y': -5}, polyline);
that's why its named "non-optimal"

2021-12-20 10:10 UTC, roflmyrlok commented on lecture_notes/10 refactoring/1-not-optimal.py
> +shift({'x': 10, 'y': -5}, polyline);
(fixed)

2021-12-28 22:04 UTC, closed without merging