Labb  10
kse-ua/introduction-to-it pull request #126
Opened 2021-12-18 00:17 UTC by DenisMilkevich

2021-12-19 16:59 UTC, tshemsedinov requested changes
Waiting for more optimizations

2021-12-19 16:59 UTC, tshemsedinov commented on lecture_notes/10 refactoring/1-not-optimal.py
> +    {'x': 0, 'y': 0},
```suggestion
    { 'x': 0, 'y': 0 },
```

2021-12-19 16:59 UTC, tshemsedinov commented on lecture_notes/10 refactoring/1-not-optimal.py
> +shift({'x': 10, 'y': -5}, polyline)
Improve indentation and formatting

2021-12-19 16:59 UTC, tshemsedinov commented on lecture_notes/10 refactoring/3 - step.py
> +        return point
Try not to change incoming parameters

2021-12-19 16:59 UTC, tshemsedinov commented on lecture_notes/10 refactoring/3 - step.js
> +  //Cheking for 'True' or 'False'
Thus comments is not needed here

2021-12-20 15:04 UTC, DenisMilkevich commented on lecture_notes/10 refactoring/1-not-optimal.py
> +shift({'x': 10, 'y': -5}, polyline)
Done

2021-12-22 09:34 UTC, closed without merging