Lab 8
kse-ua/introduction-to-it pull request #27
Opened 2021-12-01 08:43 UTC by YaroslavKSE

Homework

2021-12-01 13:14 UTC, tshemsedinov requested changes
Fix linter errors and warnings

2021-12-01 15:03 UTC, YaroslavKSE commented on lecture_notes/08 collections/6-set.py
> +        return False
Improved naming, refactored it
P.s see in 'Update 6-set Python'

2021-12-01 15:08 UTC, YaroslavKSE commented on lecture_notes/08 collections/7-dict.py
> +        return False
Fixed problems
See in "Update 7-dict Python"

2021-12-03 07:45 UTC, YaroslavKSE commented
> Fix linter errors and warnings

Fixed

2021-12-10 20:33 UTC, closed without merging