lab 8
kse-ua/introduction-to-it pull request #49
Opened 2021-12-03 12:25 UTC by vnikiforova

2021-12-03 12:35 UTC, tshemsedinov requested changes
- Don't write python code in js files, make copies
- Improve code style, fix all linter errors (see tab `Checks`)

2021-12-03 12:35 UTC, tshemsedinov commented on lecture_notes/08 collections/1-array.js
> +'use strict';
`'use strict';` should be always at the beginning of the file or beginning of the function

2021-12-03 12:35 UTC, tshemsedinov commented on lecture_notes/08 collections/4-concat.js
> +const ArrLowerCase2 = ['w', 'o', 'r', 'l', 'd'];
Rename to `greeting` and `target`

2021-12-03 12:35 UTC, tshemsedinov commented on lecture_notes/08 collections/4-concat.js
> +const UpperCase2 = ArrLowerCase2.map(name => name.toUpperCase());
Code duplication

2021-12-10 08:24 UTC, closed without merging

2021-12-10 08:25 UTC, vnikiforova commented
okey